version: '3.3'

services:
    # PostgreSQL
    db:
        image: postgres:13
        command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
        environment:
            # IMPORTANT: these three params must be the same as POSTGRES_USERNAME, POSTGRES_PASSWORD, POSTGRES_DB
            # below in 'web' service respectively
            POSTGRES_USER: 'multiomics'
            POSTGRES_PASSWORD: 'multiomics'
            POSTGRES_DB: 'multiomics'
            POSTGRES_HOST_AUTH_METHOD: 'trust'
        volumes:
            - postgres_data:/var/lib/postgresql/data/
            - ./config/postgres/postgres.conf:/etc/postgresql/postgresql.conf
        # There's a problem with IPVS connections timeout.
        # See: https://github.com/moby/moby/issues/37466 or https://stackoverflow.com/a/64507844/7058363
        deploy:
            endpoint_mode: dnsrr

    # MongoDB Server
    mongo:
        image: mongo:4.2
        environment:
            # IMPORTANT: these three params must be the same as MONGO_USERNAME, MONGO_PASSWORD, MONGO_DB
            # below in 'web' service respectively
            MONGO_INITDB_ROOT_USERNAME: 'multiomics'
            MONGO_INITDB_ROOT_PASSWORD: 'multiomics'
            MONGO_INITDB_DATABASE: 'multiomics'
        # Sets the config file
        command: --config /etc/mongo/mongod.conf
        volumes:
            - mongo_data:/data/db
            - mongo_config:/data/configdb
            - ./config/mongo/mongod.conf:/etc/mongo/mongod.conf

    # Redis Server for Websockets connections
    redis:
        image: redis:6.0.8
        volumes:
            - redis_data:/data

    # Django Proxy Server
    nginx:
        image: nginx:1.19.3
        ports:
            - '80:8000'
            # - 443:443 # Uncomment for HTTPS support
        volumes:
            - ./config/nginx/conf.d:/etc/nginx/conf.d
            - ./config/nginx/certificates:/etc/nginx/certificates
            - static_data:/static
            - media_data:/media
        depends_on:
            - web

    # Celery worker for correlation analysis
    correlation-analysis-worker:
        image: omicsdatascience/multiomix-celery-worker:5.1.0
        depends_on:
            - db
            - mongo
        volumes:
            - media_data:/src/media
        environment:
            # Celery parameters
            QUEUE_NAME: 'correlation_analysis'  # This MUST NOT be changed
            CONCURRENCY: 2

            # NOTE: in case of changes in the 'web', PostgreSQL and/or MongoDB connection parameters, they MUST be
            # changed here too!

    # Celery worker for feature selection experiments
    fs-experiments-worker:
        image: omicsdatascience/multiomix-celery-worker:5.1.0
        depends_on:
            - db
            - mongo
        volumes:
            - media_data:/src/media
        environment:
            # Celery parameters
            QUEUE_NAME: 'feature_selection'  # This MUST NOT be changed
            CONCURRENCY: 2

            # NOTE: in case of changes in the 'web', PostgreSQL and/or MongoDB connection parameters, they MUST be
            # changed here too!


    # Celery worker for statistical validations and trained models
    stats-worker:
        image: omicsdatascience/multiomix-celery-worker:5.1.0
        depends_on:
            - db
            - mongo
        volumes:
            - media_data:/src/media
        environment:
            # Celery parameters
            QUEUE_NAME: 'stats'  # This MUST NOT be changed
            CONCURRENCY: 2

            # NOTE: in case of changes in the 'web', PostgreSQL and/or MongoDB connection parameters, they MUST be
            # changed here too!

    # Django Backend Server
    web:
        image: omicsdatascience/multiomix:5.1.0
        # environment:
            # ENABLE_SECURITY: 'true'
            # LISTEN_PORT=8000
            # LISTEN_IP=0.0.0.0
            # DJANGO_SETTINGS_MODULE: 'multiomics_intermediate.settings_prod'
            # RESULT_DATAFRAME_LIMIT_ROWS: 300000
            # TABLE_PAGE_SIZE: 10

            # PostgreSQL DB connection parameters (MUST match the parameters defined in the "db" service above)
            # POSTGRES_USERNAME: 'multiomics'
            # POSTGRES_PASSWORD: 'multiomics'
            # POSTGRES_HOST: 'db'
            # POSTGRES_PORT: 5432
            # POSTGRES_DB: 'multiomics'

            # Mongo DB connection parameters (MUST match the parameters defined in the "mongo" service above)
            # MONGO_USERNAME: 'multiomics'
            # MONGO_PASSWORD: 'multiomics'
            # MONGO_HOST: 'mongo'
            # MONGO_PORT: 27017
            # MONGO_DB: 'multiomics'

            # Redis
            # REDIS_HOST: 'redis'
            # REDIS_PORT: 6379
            #
            # For logging (by default LOG_FILE_PATH is /logs)
            # LOG_FILE_PATH: /path/to/folder/log
        volumes:
            - static_data:/src/static
            - media_data:/src/media
            - logs_data:/logs
        depends_on:
            - db
            - mongo
            - correlation-analysis-worker
            - fs-experiments-worker
            - stats-worker

volumes:
    mongo_data:
        external:
            name: 'multiomics_intermediate_mongo_data'
    mongo_config:
        external:
            name: 'multiomics_intermediate_mongo_config'
    postgres_data:
        external:
            name: 'multiomics_intermediate_postgres_data'
    redis_data:
        external:
            name: 'multiomics_intermediate_redis_data'
    static_data:
        external:
            name: 'multiomics_intermediate_static_data'
    media_data:
        external:
            name: 'multiomics_intermediate_media_data'
    logs_data:
        external:
            name: 'multiomics_intermediate_logs_data'            

